### ISSUE TITLE
Files referenced in README.md and run.sh do not exist

### ISSUE THREAD

**Issue by Kaljurand** [ikiissel/synthts_et#3]
Include a working example in `README.md` and in `run.sh`. Currently `sisend.txt` and `eva003` do not exist. I'd propose something like:

```
bin/synthts_et -lex dct/et.dct -lexd dct/et3.dct -o out_tnu.wav -f in.txt -m htsvoices/eki_et_tnu.htsvoice 
bin/synthts_et -lex dct/et.dct -lexd dct/et3.dct -o out_eva.wav -f in.txt -m htsvoices/eki_et_eva.htsvoice
aplay out_tnu.wav
aplay out_eva.wav
```

**Comment by ikiissel** [comment]
Should be fixed now. Left "eva" out from examples as it is buggy and i dont know the reason.
And thanks for reporting.
